---
title: "Workshop 3 - R Markdown and Workshop 4 - Data Wrangling"
author: "Suzanne Nicholas"
date: '2022-03-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

### Data wrangling


```{r}

survey<-read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv")


country<-survey %>%
  distinct(country)

survey%>%count(country, sort=TRUE)

survey_short<-survey%>%
  filter(
    country=="United States" | 
      country=="USA" | 
      country=="US"|
      country=="U.S."|
      country=="United States of America"|
      country=="Usa"
    )


survey_short%>%filter(
  annual_salary>50000 &
    gender=="Woman"
)


survey_short%>%
  select(how_old_are_you, industry, annual_salary, gender)%>%
  filter(gender=="Woman")%>%
  count(industry, sort = TRUE)


```



```{r}

#data loading

data<-read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv")

data%>%head()


```


